### ISSUE TITLE
Semantic of shifts

### ISSUE THREAD

**Issue by lforg37** [yuguen/hint#1]
We need to define the good checks to do for right shifts.

In particular, should we allow to shift a Wrapper<W, ...> by a $Wrapper<S, false> if S > ceil(log2(W)) ?

Currently, shifter_sticky does an optimisation for this case by grouping the extra bits and zeroing the result if any of them. There is a risk to hide a bad dimensioned shift value signal, is there a good reason not to circumvent that risk ?

**Comment by lforg37** [comment]
@yuguen

**Comment by yuguen** [comment]
I think that every right shift should be allowed, but no bit should be zeroed.
Meaning that the output of a shift should always be W+pow2(S)-1 bits.
The only case where we want to throw bits away would be is the combined shifter+sticky, with an option to not compute the sticky... 
I'm not very clear about it.
